name: Tests and checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt
      - name: Generate resources
        run: |
          scripts/common/generate-resources.sh
      - name: Run unit tests for fk.core
        run: |
          PYTHONPATH=src coverage run -m xmlrunner -o test-results discover -v fk.tests
      - name: Publish test report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'test-results/TEST-*.xml'
          include_passed: true
      - name: Upload code coverage to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger e2e tests (external)
        run: |
          curl --version

  run-e2e-tests:
    runs-on: ubuntu-22.04
    needs: run-tests
    steps:
      - name: Launch e2e tests
        env:
          REMOTE_URL: ${{ secrets.REMOTE_URL }}
          REMOTE_USER_TOKEN: ${{ secrets.REMOTE_USER_TOKEN }}
          REMOTE_JOB_TOKEN: ${{ secrets.REMOTE_MAIN_JOB_TOKEN }}
        run: |
          curl -I -u "github-trigger:$REMOTE_USER_TOKEN" "$REMOTE_URL/job/gh-main/build?token=$REMOTE_JOB_TOKEN" 2>/dev/null > /dev/null

  call-build:
    needs: run-tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
        compiler: [nuitka]
    uses: flowkeeper-org/fk-desktop/.github/workflows/build.yml@main
    with:
      os: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
    secrets: inherit

  update-rc:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Update RC tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: rc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Unzip artifacts
        shell: bash
        run: |
          echo "Before unzip"
          ls -al          
          unzip dist-macos-15-nuitka-all
          unzip dist-ubuntu-24.04-nuitka-all
          unzip dist-windows-2025-nuitka-all
          echo "After unzip"
          ls -al
          rm dist-macos-15-nuitka-all
          rm dist-ubuntu-24.04-nuitka-all
          rm dist-windows-2025-nuitka-all
          echo "After cleanup / before upload"
          ls -al
#      - name: Update RC preview
#        uses: johnwbyrd/update-release@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          files: "*.*"
#          release: rc
