name: Manual build - all

on:
  workflow_dispatch:

jobs:
  call-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, ubuntu-24.04, ubuntu-22.04, ubuntu-26.04-arm, ubuntu-24.04-arm, ubuntu-22.04-arm, macos-26-intel, macos-15-intel, macos-26, macos-15, macos-14, windows-2025, windows-2022, windows-11-arm]
        compiler: [nuitka, pyinstaller]
        exclude:
          - os: windows-11-arm
            compiler: nuitka
    uses: flowkeeper-org/fk-desktop/.github/workflows/build.yml@rc-1.1.0
    with:
      os: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
    secrets: inherit
