name: Nightly job

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  call-scan:
    uses: flowkeeper-org/fk-desktop/.github/workflows/scan-release.yml@main
    with:
      release: ''
    secrets: inherit
    permissions:
      contents: write
