name: Build binaries

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Notification text'
        required: true
        default: 'Hello, World!'
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}ww
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "${{ inputs.text }}"