name: Release new version

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  checks: write

jobs:
  call-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm, macos-15, macos-14, macos-13, windows-2025, windows-2022, windows-2019]
        compiler: [nuitka, pyinstaller]
        exclude:
          - os: macos-13
            compiler: nuitka
    uses: flowkeeper-org/fk-desktop/.github/workflows/build.yml@rc-0.10.0
    with:
      os: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
    secrets: inherit

  release:
    needs: call-build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm, macos-15, macos-14, macos-13, windows-2025, windows-2022, windows-2019]
        compiler: [nuitka, pyinstaller]
        exclude:
          - os: macos-13
            compiler: nuitka
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.compiler }}-all
          path: .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./*"
