name: Scan release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release to scan, e.g. v0.10.0. Empty means latest.'
        required: false
        default: ''
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download binaries
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE: ${{ inputs.release }}
        run: scripts/common/download-release.sh
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Scan binaries
        shell: bash
        env:
          VTCLI_APIKEY: ${{ secrets.VTCLI_APIKEY }}
        run: |
          pip install vt-py
          SCAN_STATUS=$(python3 scripts/windows/vtscan.py downloads/flowkeeper-0.10.0-windows-2025-pyinstaller-standalone.exe)
          echo "$SCAN_STATUS"
          echo "SCAN_STATUS=$(SCAN_STATUS)" >> $GITHUB_ENV
      - name: Post message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Downloaded and extracted all necessary binaries:\n${{ env.SCAN_STATUS }}"
