name: Scan release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release to scan, e.g. v0.10.0. Empty means latest.'
        required: false
        default: ''
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download binaries
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE: ${{ inputs.release }}
        run: scripts/common/download-release.sh
      - name: Scan binaries
        shell: bash
        run: |
          echo "SCAN_STATUS=$(ls -al)" >> $GITHUB_ENV
      - name: Post message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Downloaded and extracted all necessary binaries:\n${{ env.SCAN_STATUS }}"
